language: php

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - DATAVASE_URL="mysql://travis:@127.0.0.1/test?serverVersion=5.7"

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SYMFONY_REQUIRE=^4
        - php: 7.4
          env: SYMFONY_REQUIRE=^5
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
        - env: STABILITY="dev"

before_install:
    - composer self-update

install:
    - composer require symfony/flex --no-update
    - composer install --prefer-source
    - vendor/bin/simple-phpunit install

script:
    - composer cs
    - composer static
    - composer validate --strict --no-check-lock
    - vendor/bin/simple-phpunit $PHPUNIT_FLAGS
